version: '3.5' # composeファイルのバージョン
services:
  api: # サービス名
    build: # ビルドに使うDockerファイルのパス
      context: ./api
      dockerfile: Dockerfile
    container_name: todo-api
    volumes: # マウントディレクトリ
      - ./api/todos:/go/todos
      - ../ca-saki-tomita-test-todoSqlClientKey.json:/go/ca-saki-tomita-test-todoSqlClientKey.json
    tty: true # コンテナの永続化
    ports:
      - "0.0.0.0:8081:8081"
    env_file: # .envファイル
      - ./api/build/.go_env
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /go/ca-saki-tomita-test-todoSqlClientKey.json

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
      target: vue-local
    command: yarn serve
    container_name: todo-web
    ports:
      - "8080:8080"
    expose:
      - "8080"
    volumes:
      - ./web/app:/app
    tty: true
    depends_on:
      - api
