version: "3.4"

services:
  vue:
    build:
      context: .
      dockerfile: ../../ohikkosi/vue/Dockerfile
    container_name: app
    ports:
      - "8080:8080"
    expose:
      - "8080"
    volumes:
      - ./app:/app
    working_dir: /app
    tty: true
    stdin_open: true
