version: '3' # composeファイルのバージョン
services:
  api: # サービス名
    build: # ビルドに使うDockerファイルのパス
      context: .
      dockerfile: Dockerfile
    container_name: todo-api
    volumes: # マウントディレクトリ
      - ./todos:/go/todos
      - ../../ca-saki-tomita-test-todoSqlClientKey.json:/go/ca-saki-tomita-test-todoSqlClientKey.json
    tty: true # コンテナの永続化
    ports:
      - "0.0.0.0:8081:8081"
    env_file: # .envファイル
      - ./build/.go_env
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /go/ca-saki-tomita-test-todoSqlClientKey.json